services:

  postgres:
    image: "postgres:alpine"
    attach: false
    container_name: postgres_123_devchalagne_24
    volumes:
      - ./.db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      default:
        aliases:
          - postgres
    ports:
      - 5432:5432

  migrations:
    image: 'liquibase/liquibase'
    attach: true
    container_name: migrations_123_devchalagne_24
    volumes:
      - ./migrations/:/liquibase/changelog/:ro
    command: --defaults-file=/liquibase/changelog/liquibase.properties update
    depends_on:
      postgres:
        condition: service_started

  web:
    container_name: web_123_devchalagne_24
    build:
      context: ./
      target: production
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_started
      migrations:
        condition: service_completed_successfully

    environment:
      - POSTGRES_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres?sslmode=allow&search_path=public
      - POSTGRES_PWD=mysecretpassword

  tests:
    build:
      context: ./tests
    depends_on:
      - web
    environment:
      - SERVICE_URL=http://web:8080
