services:

  postgres:
    image: "postgres:alpine"
    attach: false
    volumes:
      - ./.db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      default:
        aliases:
          - postgres
    ports:
      - 5432:5432

  migrations:
    image: 'liquibase/liquibase'
    attach: true
    volumes:
      - ./migrations/:/liquibase/changelog/:ro
    command: --defaults-file=/liquibase/changelog/liquibase.properties update
    depends_on:
      postgres:
        condition: service_started

  whisper:
    build:
      context: ./services/whisper
    stop_grace_period: 1s
    ports:
      - '8081:8081'
    volumes:
      - ./contrib/whisper.cpp/models/:/models
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://whisper:8081"]
      interval: 1s
      retries: 10

  nlp:
    build:
      context: ./services/nlp
    stop_grace_period: 1s
    ports:
      - '8082:8080'
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://nlp:8080/health"]
      interval: 1s
      retries: 10

  web:
    build:
      context: ./
      target: production
    ports:
      - '8080:8080'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_started
      migrations:
        condition: service_completed_successfully
      whisper:
        condition: service_healthy
      nlp:
        condition: service_healthy
    environment:
      - POSTGRES_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres?sslmode=allow&search_path=public
      - POSTGRES_PWD=mysecretpassword
      - WHISPER_URL=http://whisper:8081
      - NLP_URL=http://nlp:8080

  tests:
    build:
      context: ./tests
    depends_on:
      - web
    environment:
      - SERVICE_URL=http://web:8080
